// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const supabaseUrl = "https://ilwkvpafhztplywtkkwp.supabase.co";
const supabaseKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imlsd2t2cGFmaHp0cGx5d3Rra3dwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3MzMyNTk0MDMsImV4cCI6MjA0ODgzNTQwM30.aX-0jlIHBkG-BKAuWQnLHBiEkvFAqBJ0YuAy3vRuE_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(supabaseUrl, supabaseKey);